steps:
  - name: 'hashicorp/terraform:1.5.7'
    args:
      - 'init'
  - name: 'hashicorp/terraform:1.5.7''
    args:
      - 'apply'
      - '-auto-approve'
options:
  logging: CLOUD_LOGGING_ONLY 
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
