steps:
  - name: 'gcr.io/cloud-builders/terraform:1.5.7'
    args:
      - 'init'
  - name: 'gcr.io/cloud-builders/terraform:1.5.7'
    args:
      - 'apply'
      - '-auto-approve'
options:
  logging: CLOUD_LOGGING_ONLY 
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
